version: "3"

networks:
  zeebe_network:
    driver: bridge

services:
  node0:
    container_name: zeebe_broker_1
    image: camunda/zeebe:1.3.2
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_NODEID=0
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../lib/zeebe-hazelcast-exporter-1.1.0-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter-1.1.0-jar-with-dependencies.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
  node1:
    container_name: zeebe_broker_2
    image: camunda/zeebe:1.3.2
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_NODEID=1
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502
    # volumes:
    #   - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe_network
    depends_on:
      - node0
  node2:
    container_name: zeebe_broker_3
    image: camunda/zeebe:1.3.2
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_NODEID=2
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502
    # volumes:
    #   - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe_network
    depends_on:
      - node1

  elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
       container_name: elasticsearch
       environment:
           - cluster.name=camunda-cloud
           - discovery.type=single-node
           - bootstrap.memory_lock=true
           - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       ulimits:
           memlock:
               soft: -1
               hard: -1
       volumes:
           - elastic:/usr/share/elasticsearch/data
       networks:
           - zeebe_network

  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:latest
    environment:
      - zeebe.client.broker.contactPoint=node0:26500
      - zeebe.client.worker.hazelcast.connection=node0:5701
    volumes:
      - ./simple-monitor-application.yaml:/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - node0
    networks:
      - zeebe_network

  operate:
      image: camunda/operate:1.3.2
      container_name: operate
      environment:
          - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=node0:26500
          - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
          - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      ports:
          - 8080:8080
      networks:
          - zeebe_network
      depends_on:
          - elasticsearch


volumes:
    elastic:
        driver: local
